export * from './AdminLayout'
export * from './AdminDashboardPage'
export * from './StudentManagementPage'
export * from './LecturerManagementPage'
export * from './SchoolManagement'
export * from './SessionManagement'
export * from './AdminUploadPage'
export * from './ViewPage'